// Re-export from new prometheus hooks file
export {
  useGrafanaUrl,
  usePrometheusAlerts,
  usePrometheusSilences,
  useAlertmanagerAlerts,
  usePrometheusRules,
  useFlattenedRules,
  useSilence,
  useCreateSilence,
  useDeleteSilence,
  type GrafanaUrl,
  type PrometheusAlertLabels,
  type PrometheusAlertAnnotations,
  type PrometheusAlert,
  type PrometheusAlertGroup,
  type AlertmanagerAlertStatus,
  type AlertmanagerAlert,
  type PrometheusRule,
  type PrometheusRuleGroup,
  type PrometheusRulesResponse,
  type AlertmanagerSilenceMatcher,
  type AlertmanagerSilenceStatus,
  type AlertmanagerSilence,
} from './use-prometheus';
